name: 'Workflow Run'
description: 'Schedule a StackGuardian Workflow Run'
author: 'StackGuardian'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  orgId:
    required: true
    description: 'StackGuardian Organization Id'
  workflowGroupId:
    required: true
    description: 'Workflow Group Id'
  workflowId:
    required: true
    description: 'Workflow Id'
  apiKey:
    required: true
    description: 'StackGuardian API Key'
runs:
  using: 'node12'
  main: 'dist/index.js'
