on: [push]
jobs:
  execute-sg-cli:
    runs-on: ubuntu-latest
    name: StackGuardian Github Action
    steps:
      - name: StackGuardian/workflow-run-action
        uses: ./ # Uses an action in the root directory
        id: StackGuardian-CLI
        with:
          operation: "workflow help"